[theme]
primaryColor = "#FF9900"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F6FA"
textColor = "#0B1F3A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
